### ISSUE TITLE
Struggling with Debian

### ISSUE THREAD

**Issue by nguxx** [Zwyx/bepo-xxerty#2]
Hi,

Tried on three Debian (11 then 12). One is working perfectly, others not. They are sharing the same files (complete, fr, evdev.xml) witch are  working on the one witch is OK. What am I missing ?

TL;DR

Sur une première machine Debian en "testing" (donc Debian 12) qui est déjà ancienne et bien rodée (pleine de logiciels sédimentés au fil du temps) ça marche.
Je crée d’autres Debian en "testing" aussi. J’essaie la même manip sur les 3 fichiers, impossible de démarrer en GUI, machine bloquée.
Je copie les 3 fichiers de la machine qui fonctionne sur les nouvelles machines, pareil, impossible de démarrer.
Auriez-vous une idée de ce qui permet à la machine plus ancienne de fonctionner ? Un paquet ou une librairie en plus qu’il n’y aurait pas sur les nouvelles ?
Merci

**Comment by Zwyx** [comment]
Hi @nguxx, sorry to hear that you're having trouble, however I have no idea why your setup isn't working unfortunately. It's surprising that the new machines can't start with the new files. I don't remember ever experiencing that. The worst I had was a broken keyboard layout.

All I can say is that bépo-code still works well for me on Ubuntu 22.04 (Ubuntu is Debian based). Before, I used bépo-code on MX Linux (also Debian based) until last year when I switched because of trouble getting MX working on very recent hardware.

Can you try with different OSs? Do you know if Debian recently changed an important feature related to xkb?

Configuring xkb is so tricky and painful... what works for someone might not work for another person with seemingly the same configuration.

I'm curious, have you been using bépo-xxerty for a while?
